name: calliope-australia-snakemake-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.12
  - mypy >=1.15.0
  - ruff >=0.11.9
  - snakefmt >=0.11.0
  - conda >=25.3.1
  - snakemake-minimal >=9.3.4
  - ipdb >=0.13.13
  - pandas = 2.2.3
  - pyarrow = 20.0.0
  - ipython = 9.0.0
